defmodule Storex.Socket do
  @moduledoc """
    Socket connection handler.

    Error codes:
    - `4000`: Store is not set.
    - `4001`: Store is not defined or can't be compiled.
  """

  # A diff produced by somebody else's mutation on a store this session shares.
  # It carries no `request`, because this session did not ask for it — the
  # client applies the diff and resolves nothing.
  @doc false
  def diff_handle(store, diff, %{session: session} = state) do
    %{
      type: "mutation",
      session: session,
      store: store,
      diff: diff,
      request: nil
    }
    |> Jason.encode!()
    |> (&{:text, &1, state}).()
  end

  @doc false
  def message_handle(%{type: "ping"} = message, state) do
    message =
      Map.put(message, :type, "pong")
      |> Jason.encode!()

    {:text, message, state}
  end

  def message_handle(%{store: nil}, state) do
    {:close, 4000, "Store is not set.", state}
  end

  def message_handle(%{type: "join"} = message, state) do
    with {:get_module, {:ok, _}} <- {:get_module, Storex.Store.resolve(message.store)},
         {:add_store, {:ok, _}} <-
           {:add_store,
            Storex.Supervisor.add_store(message.store, state.session, state.pid, message.data)},
         {:store_state, {:ok, store_state}} <-
           {:store_state, Storex.Supervisor.get_store_state(state.session, message.store)} do
      message =
        Map.put(message, :data, store_state)
        |> Map.put(:session, state.session)
        |> Jason.encode!()

      {:text, message, state}
    else
      {step, {:error, error_message}} when step in [:add_store, :store_state] ->
        %{
          type: "error",
          session: state.session,
          store: message.store,
          error: error_message,
          request: Map.get(message, :request, nil)
        }
        |> Jason.encode!()
        |> (&{:text, &1, state}).()

      _ ->
        {:close, 4001, "Store '#{message.store}' is not defined or can't be compiled.", state}
    end
  end

  # The `session` carried by the frame is never used to resolve the store. It is
  # supplied by the client, so trusting it would let any socket mutate any other
  # session's store. Only `state.session`, generated by the handler for this
  # connection, addresses a store. Mutating another session deliberately is what
  # `Storex.mutate/3` and `Storex.mutate/4` are for.
  def message_handle(%{type: "mutation", store: store} = message, %{session: session} = state) do
    Storex.Supervisor.mutate_store(
      session,
      store,
      message.data.name,
      message.data.data
    )
    |> case do
      {:ok, diff} ->
        %{
          type: "mutation",
          session: session,
          store: store,
          diff: diff,
          request: Map.get(message, :request, nil)
        }

      {:ok, reply_message, diff} ->
        %{
          type: "mutation",
          session: session,
          store: store,
          diff: diff,
          message: reply_message,
          request: Map.get(message, :request, nil)
        }

      {:error, error} ->
        %{
          type: "error",
          session: session,
          store: store,
          error: error,
          request: Map.get(message, :request, nil)
        }
    end
    |> Jason.encode!()
    |> (&{:text, &1, state}).()
  end
end
